# Blank-Grabber
vУ меня есть ошибка, которая гласит "Traceback (последний вызов последний): Файл "E:\blank grabber\Blank-Grabber-main\Blank Grabber\gui.py", строка 12, в импорте customtkinter как ctk ModuleNotFoundError: No module named 'customtkinter'"
